/* @include "data/accounts.js" */
/* @include "data/customers.js" */
/* @include "data/contacts.js" */
/* @include "data/tasks.js" */
/* @include "data/approvals.js" */
/* @include "data/campaigns.js" */
/* @include "data/organization.js" */
/* @include "modules/_app-shell/state.js" */
/* @include "data/organization-history.js" */
/* @include "data/task-state.js" */
/* @include "data/notifications.js" */
/* @include "data/maintenance.js" */
/* @include "data/archive.js" */
/* @include "data/regions.js" */
/* @include "data/customer-settings.js" */
/* @include "data/imports.js" */
/* @include "data/platform.js" */
/* @include "data/projects.js" */
/* @include "data/project-instructors.js" */
/* @include "data/project-packages.js" */
/* @include "data/platform-companies.js" */
/* @include "modules/_app-shell/runtime.js" */
/* @include "modules/m02-customer-operations/page.js" */
/* @include "modules/m01-dashboard/page.js" */
/* @include "modules/m04-approvals/presentation.js" */
/* @include "modules/_app-shell/overlays.js" */
/* @include "data/customer-organization.js" */
/* @include "modules/m02-customer-operations/scoped-records.js" */
/* @include "modules/m03-maintenance/page.js" */
/* @include "modules/m04-approvals/page.js" */
/* @include "modules/m05-archive/page.js" */
/* @include "modules/m06-organization/page.js" */
/* @include "modules/m10-imports/page.js" */
/* @include "modules/m11-project-management/page.js" */
/* @include "modules/m02-customer-operations/details.js" */
/* @include "modules/m03-maintenance/details.js" */
/* @include "modules/m02-customer-operations/records.js" */
/* @include "modules/m04-approvals/interactions.js" */
/* @include "modules/m05-archive/interactions.js" */
/* @include "modules/m06-organization/account-actions.js" */
/* @include "modules/_app-shell/account.js" */
/* @include "modules/m08-regions/interactions.js" */
/* @include "modules/m09-customer-settings/interactions.js" */
/* @include "modules/m10-imports/interactions.js" */
/* @include "modules/m11-project-management/interactions.js" */
/* @include "modules/m02-customer-operations/transfers.js" */
/* @include "modules/m03-maintenance/task-actions.js" */
/* @include "modules/m08-regions/page.js" */
/* @include "modules/m02-customer-operations/customer-tree.js" */
/* @include "modules/m09-customer-settings/page.js" */
/* @include "modules/m08-regions/forms.js" */
/* @include "data/permissions.js" */
/* @include "modules/m07-permissions/page.js" */
/* @include "modules/m06-organization/interactions.js" */
/* @include "modules/_app-shell/events.js" */
/* @include "modules/_app-shell/notifications.js" */
/* @include "modules/_app-shell/bootstrap.js" */
